{% set name = "openslide-python" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a790857a4f717002ddecf7a1b61c5cd86221c81bc9cfd444a71e4c9912cef55c

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - setuptools
  host:
    - pip
    - python
    - openslide
    - setuptools
  run:
    - pillow
    - python
    - openslide
    - setuptools

test:
  imports:
    - openslide

about:
  home: http://openslide.org/
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python interface to OpenSlide

extra:
  recipe-maintainers:
    - sarthakpati
